name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - run: npm ci

      - name: ESLint
        run: npx eslint src/**/**.ts

      - run: npm run dist

      - name: run with defaults
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts .github/**/**.yml .github/**/**.yaml

      - name: run with npx
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts .github/**/**.yml .github/**/**.yaml
          npx: 'true'

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          dirs: dist/
        if: contains(github.ref, 'refs/heads/versions/' )
