name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - run: npm ci

      - name: ESLint
        run: npx eslint src/**/**.ts __tests__/**/**.ts

      - run: npm run dist

      - name: run
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts .github/**/*.yml .github/**/*.yaml

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          dirs: dist/
        if: contains(github.ref, 'refs/heads/versions/' )
