name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - run: npm ci

      - run: npm run dist

      - name: run
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts .github/**/*.yml .github/**/*.yaml

      - uses: harveyr/gh-action-publish@releases/<version>
        with:
          dirs: dist/
        if: contains(github.ref, 'refs/heads/versions/' )
